name: CI
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Just a name'
        default: 'Jospehina'
        required: true
  push:
    branches:  [main, develop]
  pull_request:
    branches: [main ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run a online-script
        run: echo "Hello ${{ github.inputs.name }}"
        
      - name: run a multiline-script
        run: |
          echo Hello secco
          echo Hello denovo
